# Generated by Django 4.0.5 on 2022-06-09 18:47

from django.db import migrations, models
import django.db.models.deletion
import djangobft.bft.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, validators=[djangobft.bft.validators.validate_type])),
                ('slug', models.SlugField(editable=False)),
                ('email_address', models.EmailField(max_length=255)),
                ('anumbers', models.TextField(blank=True, validators=[djangobft.bft.validators.validate_anumbers], verbose_name='A-numbers')),
                ('submit_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('browser_meta', models.CharField(blank=True, editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bft.submission')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('recipients', models.TextField(validators=[djangobft.bft.validators.validate_recipients])),
                ('message', models.TextField()),
            ],
            bases=('bft.submission',),
        ),
        migrations.CreateModel(
            name='FileArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FilePathField(editable=False, max_length=500)),
                ('submit_date', models.DateTimeField(editable=False)),
                ('delete_date', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bft.submission')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('file_upload', models.FileField(max_length=500, upload_to='files/%d-%m-%Y')),
                ('file_size', models.DecimalField(decimal_places=3, editable=False, max_digits=8, verbose_name='File Size (MB)')),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bft.submission')),
            ],
        ),
    ]
